### ISSUE TITLE
Don't compile on ESP8266 arduino

### ISSUE THREAD

**Issue by KipK** [paulo-raca/ArduinoBufferedStreams#1]
Tried with ESP8266 SDK 2.3.0 for arduino, but I get an error trying to compile the demo.

> Arduino\libraries\Buffered_Streams\src\LoopbackStream.cpp: In constructor 'LoopbackStream::LoopbackStream(uint16_t)':
> 
> \Buffered_Streams\src\LoopbackStream.cpp:4:36: error: invalid conversion from 'void_' to 'uint8_t_ {aka unsigned char*}' [-fpermissive]
> 
>    this->buffer = malloc(buffer_size);
> 
> exit status 1

Best

Best

**Comment by paulo-raca** [comment]
Thanks for catching this issue.

I don't have my dev tools right now, but I believe it should work:

`this->buffer = (uint8_t*) malloc(buffer_size);`

Can you test this?

**Comment by KipK** [comment]
The cast did the trick, thanks.

With your lib I can now mirror my debug output to telnet console + Serial in few line of code. 

Thanks for your lib.

**Comment by KipK** [comment]
Thanks. I'll try in few hours.
Also I haven't reviewed your code in detail but seems I've saw hard
uint_16t in it. ESP is 32bits so Int use 4 bytes.

Cheers

Le 27 oct. 2016 13:27, "Paulo Costa" <notifications@github.com> a écrit :

Thanks for catching this issue.

I don't have my dev tools right now, but I believe it should work:

this->buffer = (uint8_t*) malloc(buffer_size);

Can you test this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/paulo-raca/ArduinoBufferedStreams/issues/1#issuecomment-256615818>,
or mute the thread

**Comment by paulo-raca** [comment]
The uint16_t is the buffer size.
64KB seems like a reasonable limit to the internal buffer, but I can change that if you need.

Code to mirror the debug output would be a great nice example. Would you mind to submit it?

**Comment by KipK** [comment]
Sure I'll share. It's in a quiet big sketch for now, I'll simplify it.

I thought the buffer size parameters was bytes. I've put 256 but if t's 64K it's far enough I guess :)

**Comment by KipK** [comment]
Here is an example Sketch you can add to your project. 

https://1drv.ms/u/s!AgQ5240erH-xhlGt1eBYhZR1Qg5D

Best

**Comment by paulo-raca** [comment]
Thanks for the PR!
