### ISSUE TITLE
Add .print() .println() .printf()

### ISSUE THREAD

**Issue by Sterpa** [paulo-raca/ArduinoBufferedStreams#4]
Hi!
Could you please add .print() .println() .printf() functions to PipedStream.h?

I have to use some callbacks for PipedStream.println() but don't understand, how to do this if .print() is a part of print.h but not stream.h

**Comment by paulo-raca** [comment]
There is an inheritance chain here: Print -> Stream -> PipedStream.

In other words, PipedStream already supports all operations supported by Print and Stream classes, including `print` and `println` (`printf` is supported in some targets, like esp8266, but unfortunately not on AVR)
