### ISSUE TITLE
Is it possible to change the size of the buffer without modifying the library?

### ISSUE THREAD

**Issue by misaalanshori** [paulo-raca/ArduinoBufferedStreams#9]
Is it possible to change the size of the buffer used by the loopback stream from my own code? If I understand the code right then I think the default currently is 64 bytes? I need to change that to something bigger, but I'm not sure how to do it. Is this possible? 

Thanks

**Comment by paulo-raca** [comment]
Yes, you can specify the size in the constructors.

E.g.

```
LoopbackStream buffer(4096);
```

**Comment by misaalanshori** [comment]
Ah okay, thank you so much!

**Comment by misaalanshori** [comment]
Hey, sorry. I have another question. Is something like `Serial.write(buf, len)` not yet implemented?
